// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config as loadEnv } from "dotenv";
import { defineConfig } from "prisma/config";

// Supabase setup keeps connection strings in .env.local (see .env.example). Prisma 7 no
// longer auto-loads .env files, so load it explicitly here for DATABASE_URL / DIRECT_URL.
loadEnv({ path: ".env.local" });

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Migrations / introspection use the session-mode pooler (DIRECT_URL).
    // The runtime PrismaClient should connect via an adapter built with the
    // transaction-mode pooler (DATABASE_URL). See https://pris.ly/d/config-datasource
    url: process.env["DIRECT_URL"],
  },
});
